# Site settings
title: DentalSavers
description: "Gap Free Preventative Dentistry"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.png

# Hero
hero: 
    hero_img: heromain.jpg
    hero_title: DentalSavers
    hero_description: Gap Free Preventative Dentistry

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 07 5495 1888
    emergency: 07 5495 1888
    email: Reception@dentalsavers.com.au
    address: 4/111 William Berry Drive, Morayfield QLD 4506

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 4/111 William Berry Drive, Morayfield QLD 4506
    address_details: svg/min/logo.png

# Social settings
facebook: http://facebook.com
# twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: ©DentalSavers - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
